spring:
  application:
    name: customercore
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate : true
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8083

grpc:
  server:
    port: 9092
  default-scheme: discovery
  client:
    GLOBAL:
      negotiation-type: PLAINTEXT
#    template-service:
#      address: static://localhost:9090  # Update this to your Template Service gRPC server
#    customer-core:
#      address: static://localhost:9092

